server:
  port: 7010
spring:
  profiles:
    active: dev
  application:
    name: beecube-app
  config:
    import:
      - optional:nacos:jeecg.yaml

  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}