spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://jeecg-boot-mysql:3306/beecube-paimai?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: beecube-paimai
          password: jKGpNcaBpScMmkLF
          driver-class-name: com.mysql.cj.jdbc.Driver