spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://jeecg-boot-mysql:3306/beecube-paimaihy?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: beecube-paimai
          password: jKGpNcaBpScMmkLF
          driver-class-name: com.mysql.cj.jdbc.Driver



im:
  server-ip: 127.0.0.1
  tcpPort: 8902
  udpPort: 7902
  websocketPort: 3100
  debug: true